"""Loading a scenario file and the decorator."""
import json

import pytest

from monocle_test_tools.scenarios.scenario import Scenario, ScenarioError, load_scenarios, monocle_scenarios

ENTRY = {
    "test_name": "book_flight.withhold.date",
    "scenario": "Book a flight from one airport to another on a date",
    "persona": "terse",
    "params": [
        {"name": "source", "value": "Bombay", "description": "source airport", "is_initial": True},
        {"name": "date", "value": "22 Oct 2026", "description": "travel date", "is_initial": False},
    ],
    "success_criteria": "The agent confirms the flight is booked.",
    "target_description": "A travel agent",
}


def write(tmp_path, entries, name="scenarios.json"):
    path = tmp_path / name
    path.write_text(json.dumps(entries), encoding="utf-8")
    return str(path)


def test_load_scenarios_happy(tmp_path):
    scenarios = load_scenarios(write(tmp_path, [ENTRY]))
    assert len(scenarios) == 1
    scenario = scenarios[0]
    assert isinstance(scenario, Scenario)
    assert scenario.test_name == "book_flight.withhold.date"
    assert scenario.on_request_params[0].name == "date"
    assert scenario.session_id  # auto-generated by the harness model


def test_load_scenarios_rejects_duplicate_names(tmp_path):
    with pytest.raises(ScenarioError, match="duplicate test_name"):
        load_scenarios(write(tmp_path, [ENTRY, ENTRY]))


def test_load_scenarios_rejects_an_invalid_entry(tmp_path):
    bad = {**ENTRY, "max_turns": 0}
    with pytest.raises(ScenarioError, match="scenario #0 is invalid"):
        load_scenarios(write(tmp_path, [bad]))


def test_load_scenarios_requires_the_target_description(tmp_path):
    missing = {k: v for k, v in ENTRY.items() if k != "target_description"}
    with pytest.raises(ScenarioError, match="target_description"):
        load_scenarios(write(tmp_path, [missing]))


def test_load_scenarios_rejects_missing_or_empty_file(tmp_path):
    with pytest.raises(ScenarioError, match="not found"):
        load_scenarios(str(tmp_path / "nope.json"))
    with pytest.raises(ScenarioError, match="non-empty"):
        load_scenarios(write(tmp_path, []))


def test_monocle_scenarios_parametrizes_with_test_names(tmp_path):
    second = {**ENTRY, "test_name": "book_flight.persona.newcomer"}
    mark = monocle_scenarios(write(tmp_path, [ENTRY, second]))
    assert mark.name == "parametrize"
    assert mark.args[0] == "scenario"
    assert mark.kwargs["ids"] == ["book_flight.withhold.date", "book_flight.persona.newcomer"]


def test_monocle_scenarios_resolves_relative_to_the_caller(tmp_path, monkeypatch):
    write(tmp_path, [ENTRY])
    import inspect

    class Frame:
        filename = str(tmp_path / "test_x.py")

    monkeypatch.setattr(inspect, "stack", lambda: [None, Frame()])
    mark = monocle_scenarios("scenarios.json")
    assert mark.kwargs["ids"] == ["book_flight.withhold.date"]
